// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkxmPOHTc-4yTCYnBLLC8neaxvgy2h0DI',
    appId: '1:1063440862829:web:3c9b051673f69450df3964',
    messagingSenderId: '1063440862829',
    projectId: 'doorbellapp-3c6d0',
    authDomain: 'doorbellapp-3c6d0.firebaseapp.com',
    storageBucket: 'doorbellapp-3c6d0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6oHIeNhpxWOIST21eDsTjW3EZ_Rr3M2E',
    appId: '1:1063440862829:android:59e26daae21f2997df3964',
    messagingSenderId: '1063440862829',
    projectId: 'doorbellapp-3c6d0',
    storageBucket: 'doorbellapp-3c6d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBivZlau6h0Jd-5SQvRBMWEW-wYxh3rQY',
    appId: '1:1063440862829:ios:27af25af281bfef9df3964',
    messagingSenderId: '1063440862829',
    projectId: 'doorbellapp-3c6d0',
    storageBucket: 'doorbellapp-3c6d0.appspot.com',
    iosBundleId: 'com.example.doorbell',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBivZlau6h0Jd-5SQvRBMWEW-wYxh3rQY',
    appId: '1:1063440862829:ios:27af25af281bfef9df3964',
    messagingSenderId: '1063440862829',
    projectId: 'doorbellapp-3c6d0',
    storageBucket: 'doorbellapp-3c6d0.appspot.com',
    iosBundleId: 'com.example.doorbell',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkxmPOHTc-4yTCYnBLLC8neaxvgy2h0DI',
    appId: '1:1063440862829:web:76991284283acecedf3964',
    messagingSenderId: '1063440862829',
    projectId: 'doorbellapp-3c6d0',
    authDomain: 'doorbellapp-3c6d0.firebaseapp.com',
    storageBucket: 'doorbellapp-3c6d0.appspot.com',
  );
}
